pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.neoforged.net/releases/' }
        maven { url = 'https://maven.outlands.top/releases/' }
        maven { url = 'https://maven.wagyourtail.xyz/releases/' }
        gradlePluginPortal()
    }
}
rootProject.name = 'LODgen'
