modLoader="javafml"
loaderVersion="*"
license="${modLicense}"
issueTrackerURL="${modIssueTrackerUrl}"

[[mods]]
modId="${modId}"
version="${version}"
displayName="${modName}"
displayURL="${modHomepageUrl}"
logoFile="${modIcon}"
description="${modDescription}"
authors="${modAuthors}"

[[mixins]]
config="lodgen.mixins.json"

[[dependencies."${modId}"]]
modId="minecraft"
type="required"
versionRange="[${minecraft}]"
ordering="NONE"
side="BOTH"

[[dependencies."${modId}"]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies."${modId}"]]
modId="distanthorizons"
type="optional"
versionRange="[${dhVersion}]"
ordering="AFTER"
side="BOTH"

[[dependencies."${modId}"]]
modId="lss"
type="optional"
versionRange="*"
ordering="AFTER"
side="SERVER"

[[dependencies."${modId}"]]
modId="c2me"
type="optional"
versionRange="[0.4.0-alpha.0,)"
ordering="AFTER"
side="BOTH"
