modLoader="javafml"
loaderVersion="*"
license="MIT"

[[mods]]
modId="lodgen"
version="${version}"
displayName="LODgen"
description="Generates chunk-based LODs for Distant Horizons FEATURES and Voxy without saving LOD-only chunks."

[[mixins]]
config="lodgen.mixins.json"

[[dependencies.lodgen]]
modId="minecraft"
type="required"
versionRange="[${minecraft}]"
ordering="NONE"
side="BOTH"

[[dependencies.lodgen]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.lodgen]]
modId="distanthorizons"
type="optional"
versionRange="[${dhVersion}]"
ordering="AFTER"
side="BOTH"

[[dependencies.lodgen]]
modId="c2me"
type="optional"
versionRange="[0.4.0-alpha.0,)"
ordering="AFTER"
side="BOTH"
